# Generated by Django 4.2.28 on 2026-02-03 17:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('principal', 'Data Principal'), ('fiduciary', 'Data Fiduciary'), ('processor', 'CMS Processor'), ('dpo', 'Data Protection Officer')], default='principal', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_categories', models.JSONField(default=list, help_text="Categories of personal data: ['name', 'email', 'phone', etc.]")),
                ('lawful_basis', models.CharField(default='consent', help_text='Legal basis for processing (consent, contract, legal obligation, etc.)', max_length=100)),
                ('retention_period_days', models.PositiveIntegerField(default=365, help_text='How long data will be retained in days')),
                ('is_active', models.BooleanField(default=True)),
                ('fiduciary', models.ForeignKey(limit_choices_to={'role': 'fiduciary'}, on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purpose',
                'verbose_name_plural': 'Purposes',
                'db_table': 'purposes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grievance_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='general', help_text='Category: consent, data_access, data_deletion, etc.', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('against_entity', models.ForeignKey(blank=True, limit_choices_to={'role': 'fiduciary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances_against', to=settings.AUTH_USER_MODEL)),
                ('assigned_dpo', models.ForeignKey(blank=True, limit_choices_to={'role': 'dpo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'db_table': 'grievances',
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_requested', models.JSONField(default=list, help_text='List of data fields being requested')),
                ('notes', models.TextField(blank=True, null=True)),
                ('cms_status', models.CharField(choices=[('pending_cms', 'Pending CMS Review'), ('cms_approved', 'CMS Approved'), ('cms_denied', 'CMS Denied')], default='pending_cms', max_length=20)),
                ('cms_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cms_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cms_reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['processor', 'dpo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('fiduciary', models.ForeignKey(limit_choices_to={'role': 'fiduciary'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_consent_requests', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(limit_choices_to={'role': 'principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_consent_requests', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='application.purpose')),
            ],
            options={
                'verbose_name': 'Consent Request',
                'verbose_name_plural': 'Consent Requests',
                'db_table': 'consent_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_categories', models.JSONField(default=list, help_text='Categories of data consented for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('consent_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='application.consentrequest')),
                ('fiduciary', models.ForeignKey(limit_choices_to={'role': 'fiduciary'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_consents', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(limit_choices_to={'role': 'principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_consents', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='application.purpose')),
            ],
            options={
                'verbose_name': 'Consent',
                'verbose_name_plural': 'Consents',
                'db_table': 'consents',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('consent_rejected', 'Consent Rejected'), ('data_accessed', 'Data Accessed'), ('data_corrected', 'Data Corrected'), ('data_deleted', 'Data Deleted'), ('grievance_raised', 'Grievance Raised'), ('grievance_resolved', 'Grievance Resolved'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('entity_type', models.CharField(help_text='Model name: consent, consent_request, grievance, user, etc.', max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the affected entity', max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
