# Generated by Django 4.2.28 on 2026-03-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='expiry_notified',
            field=models.BooleanField(default=False, help_text='Whether the user has been notified about expiry'),
        ),
        migrations.AddField(
            model_name='consent',
            name='lifecycle_state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_cms', 'Pending CMS Review'), ('cms_approved', 'CMS Approved'), ('cms_denied', 'CMS Denied'), ('approved', 'Approved by Principal'), ('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='active', help_text='Current state in the consent lifecycle', max_length=30),
        ),
        migrations.AddField(
            model_name='grievance',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalation if status is escalated', null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sla_breached',
            field=models.BooleanField(default=False, help_text='Whether SLA has been breached'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('consent_rejected', 'Consent Rejected'), ('consent_expired', 'Consent Expired'), ('data_accessed', 'Data Accessed'), ('data_corrected', 'Data Corrected'), ('data_deleted', 'Data Deleted'), ('data_exported', 'Data Exported'), ('grievance_raised', 'Grievance Raised'), ('grievance_resolved', 'Grievance Resolved'), ('grievance_escalated', 'Grievance Escalated'), ('profile_updated', 'Profile Updated'), ('rights_request_submitted', 'Rights Request Submitted'), ('rights_request_completed', 'Rights Request Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='DataPrincipalRightsRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('access', 'Access Personal Data'), ('correction', 'Correction of Data'), ('erasure', 'Erasure (Right to be Forgotten)'), ('portability', 'Data Portability'), ('withdraw_all', 'Withdraw All Consents')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Additional details about the request')),
                ('data_to_correct', models.JSONField(blank=True, default=dict, help_text='For correction requests: {field: {old_value, new_value}}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('partially_completed', 'Partially Completed')], default='pending', max_length=30)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Notes about how the request was handled')),
                ('exported_data_url', models.URLField(blank=True, help_text='URL to download exported data (for portability requests)', null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fiduciary', models.ForeignKey(blank=True, limit_choices_to={'role': 'fiduciary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_requests_against', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(limit_choices_to={'role': 'principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='rights_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['dpo', 'processor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rights_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Principal Rights Request',
                'verbose_name_plural': 'Data Principal Rights Requests',
                'db_table': 'data_rights_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
