# Generated by Django 4.2.28 on 2026-03-06 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_consent_expiry_notified_consent_lifecycle_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('consent_request', 'New Consent Request'), ('consent_approved', 'Consent Approved'), ('consent_rejected', 'Consent Rejected'), ('consent_expiring', 'Consent Expiring Soon'), ('consent_expired', 'Consent Expired'), ('consent_withdrawn', 'Consent Withdrawn'), ('grievance_filed', 'Grievance Filed'), ('grievance_assigned', 'Grievance Assigned'), ('grievance_updated', 'Grievance Updated'), ('grievance_resolved', 'Grievance Resolved'), ('sla_breach', 'SLA Breach Alert'), ('rights_request', 'Data Rights Request'), ('system_alert', 'System Alert')], default='system_alert', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
