# Generated by Django 4.2.28 on 2026-03-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='against_entity_name',
            field=models.CharField(blank=True, help_text='Name of the organization when no specific fiduciary user is selected', max_length=255, null=True),
        ),
    ]
