# Generated by Django 4.2.28 on 2026-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_add_against_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('consent_rejected', 'Consent Rejected'), ('consent_expired', 'Consent Expired'), ('data_accessed', 'Data Accessed'), ('data_corrected', 'Data Corrected'), ('data_deleted', 'Data Deleted'), ('data_exported', 'Data Exported'), ('consent_requested', 'Consent Requested'), ('consent_withdrawn', 'Consent Withdrawn'), ('consent_enabled', 'Consent Re-enabled'), ('grievance_raised', 'Grievance Raised'), ('grievance_resolved', 'Grievance Resolved'), ('grievance_escalated', 'Grievance Escalated'), ('grievance_assigned', 'Grievance Assigned'), ('profile_updated', 'Profile Updated'), ('rights_request_submitted', 'Rights Request Submitted'), ('rights_request_completed', 'Rights Request Completed')], max_length=50),
        ),
    ]
