# Generated by Django 6.0.3 on 2026-03-10 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login Verification'), ('registration', 'Registration Verification'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('consent_confirmation', 'Consent Confirmation')], default='login', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user (null for registration/new users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='otps_email_32bf71_idx'), models.Index(fields=['expires_at'], name='otps_expires_f6308f_idx')],
            },
        ),
    ]
