# Generated by Django 4.2.29 on 2026-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_add_otp_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='against_entity_name',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('consent_rejected', 'Consent Rejected'), ('consent_expired', 'Consent Expired'), ('data_accessed', 'Data Accessed'), ('data_corrected', 'Data Corrected'), ('data_deleted', 'Data Deleted'), ('data_exported', 'Data Exported'), ('grievance_raised', 'Grievance Raised'), ('grievance_resolved', 'Grievance Resolved'), ('grievance_escalated', 'Grievance Escalated'), ('profile_updated', 'Profile Updated'), ('rights_request_submitted', 'Rights Request Submitted'), ('rights_request_completed', 'Rights Request Completed')], max_length=50),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
