# Generated by Django 6.0.3 on 2026-03-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_add_user_aadhaar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_number',
        ),
    ]
